name: ManHuntExtended
version: ${project.version}
main: latham.manhuntextended.ManHuntExtended
api-version: 1.13
commands:
    hunter:
        description: "Base command for Harbor!"
    hunterdebug:
        description: "Debug commands for ManHuntExtended"